<a href="https://colab.research.google.com/github/anchalsinha-0411/Numpy/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


#numpy


In [ ]:
import numpy as np #as keyword is used as rename
X=np.array([1,2,4])
print(X)

m= np.array([[1,2,3],[4,5,6]])
print(m)

[1 2 4]
[[1 2 3]
 [4 5 6]]


In [ ]:
m.shape

(2, 3)

In [ ]:
X.shape

(3,)

In [ ]:
n = np.arange(0,30,2) #start at 0 count up by 2,stop before 30
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [ ]:
n= n.reshape(3,5) #reshape array to be 3x5 #reshape doesnt change the original array
n

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [ ]:
l = np.linspace(0,4,9) # return 9 evenly spaced values from 0 to 4
l

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [ ]:
l.resize(3,3) #change the original array
l

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

In [ ]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
q= np.ones([2,3],int)
q

array([[1, 1, 1],
       [1, 1, 1]])

In [ ]:
q=np.ones([2,3], float)
q

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.eye(3) #4 rows and four columns with float datatype

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.eye(4) #eye function accepts only one parameter

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.eye(2.0) # 'float' object cannot be interpreted as an integer


TypeError: 'float' object cannot be interpreted as an integer

In [ ]:
y = np.array([4,5,6])
np.diag(y) #convert array to diagonal array

array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 6]])

In [ ]:
np.array([1,2,3]*3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [ ]:
np.repeat([1,2,3],3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [ ]:
p = np.ones([2,3],int)
p

array([[1, 1, 1],
       [1, 1, 1]])

In [ ]:
p = np.ones([2,3], float)
p


array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.vstack([p,2*p]) #concatnating the array which should have equal number of columns

array([[1., 1., 1.],
       [1., 1., 1.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [ ]:
np.hstack([p,2*p]) #concatnating the array which should have equal number of rows

array([[1., 1., 1., 2., 2., 2.],
       [1., 1., 1., 2., 2., 2.]])

In [ ]:
x=np.array([1,2,3])
y=np.array([4,5,6])

In [ ]:
x,y


(array([1, 2, 3]), array([4, 5, 6]))

In [ ]:
x

array([1, 2, 3])

In [ ]:
y

array([4, 5, 6])

In [ ]:
x*y

array([ 4, 10, 18])

In [ ]:
x+y

array([5, 7, 9])

In [ ]:
x//y

array([0, 0, 0])

In [ ]:
x**y

array([  1,  32, 729])

In [ ]:
print (x.dot(y))

32


In [ ]:
z=np.array([y,y**2])
print(len(z)) #number of rows of array
z

2


array([[ 4,  5,  6],
       [16, 25, 36]])

In [ ]:
z.shape

(2, 3)

In [ ]:
z=np.array([y,y**2])
z

array([[ 4,  5,  6],
       [16, 25, 36]])

In [ ]:
z.T #transpose a array row will be column and column will be row

array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])

In [ ]:
z.dtype #data type of the elements in the array

dtype('int64')

In [ ]:
z.T.shape

(3, 2)

In [ ]:
z= z.astype('f') #float
z

array([[ 4.,  5.,  6.],
       [16., 25., 36.]], dtype=float32)

In [ ]:
np.eye(4).astype('i') #int

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int32)

In [ ]:
a=np.array([-4,-2,1,3,5])

In [ ]:
a.sum()

np.int64(3)

In [ ]:
a.shape

(5,)

In [ ]:
a.dtype

dtype('int64')

In [ ]:
s=np.arange(13)**2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

In [ ]:
s[-4:]

array([ 81, 100, 121, 144])

In [ ]:
s[-5::-2]

array([64, 36, 16,  4,  0])

2-d Array

In [ ]:
r=np.arange(36)
r.resize((6,6))
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [ ]:
r[3,3:6]

array([21, 22, 23])

In [ ]:
test = np.random.randint(0,10,(4,3))
test

array([[2, 0, 2],
       [5, 1, 9],
       [3, 8, 8],
       [0, 8, 9]])

In [ ]:
test=np.random.randint(0,10,5)
test

array([9, 3, 6, 7, 0])

In [ ]:
test2 =test**2
print(test2)

for i,j in zip(test,test2):
  print(i,'+',j,'=',i+j)


[81  9 36 49  0]
9 + 81 = 90
3 + 9 = 12
6 + 36 = 42
7 + 49 = 56
0 + 0 = 0


In [ ]:
test = np.random.randint(0,10,(4,3))
test

array([[0, 6, 8],
       [3, 0, 4],
       [8, 5, 1],
       [5, 5, 1]])

In [ ]:
for row in test: #sentinal control declartion is there in range
  print(row)

[0 6 8]
[3 0 4]
[8 5 1]
[5 5 1]


In [ ]:
for column in test:
  print(column)

[0 6 8]
[3 0 4]
[8 5 1]
[5 5 1]


In [ ]:
for i in range(len(test)):
  print(test[i])

[0 6 8]
[3 0 4]
[8 5 1]
[5 5 1]


#assignment1

Q1. create a 3x3 numpy array of all True's(boolean)

In [ ]:
import numpy as np
array = np.full((3,3), True,dtype=bool)
print(array)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


Q2. Replace all odd numbers in array with -1


In [ ]:
a=np.array([1,2,3,4,5,6,7,8,9])

b=a[a % 2 == 1] = -1
print(a)

[-1  2 -1  4 -1  6 -1  8 -1]


Q3. get a common items between array1 and array2

In [ ]:
array1=np.array(['Anchal','Shashank','Yash','Mohit',])
array2=np.array(['Shashank','Anchal'])

common_items = np.intersect1d(array1, array2)
print(common_items)

['Anchal' 'Shashank']


Q4.get the positions where elements of a and b match

In [ ]:
a=np.array([1,2,3,4,5])
b=np.array([1,0,3,0,5])
np.where(a==b)


(array([0, 2, 4]),)

Q5. Swap columns 1 and 2 in the array.

In [ ]:
import numpy as np

# Assuming 'test' is the array you want to modify based on previous cells.
# If you have a different array, please replace 'test' with the correct variable name.

# Create a sample array if 'test' is not defined in the current session
try:
    test
except NameError:
    test = np.arange(9).reshape(3,3)
    print("Created a sample array 'test':")
    print(test)
    print("-" * 20)


# Swap columns 1 and 2 (remembering that indexing starts at 0)
# The slicing [:, [1, 0, 2]] selects all rows (:)
# and specifies the order of columns: column 1, then column 0, then column 2
test[:, [0, 1]] = test[:, [1, 0]]
print("Array with columns 1 and 2 swapped:")
print(test)

Created a sample array 'test':
[[0 1 2]
 [3 4 5]
 [6 7 8]]
--------------------
Array with columns 1 and 2 swapped:
[[1 0 2]
 [4 3 5]
 [7 6 8]]


Q6.swap rows 1 and 2 in the array


In [ ]:
import numpy as np

# Assuming 'test' is the array you want to modify based on previous cells.
# If you have a different array, please replace 'test' with the correct variable name.

# Create a sample array if 'test' is not defined in the current session
try:
    test
except NameError:
    test = np.arange(9).reshape(3,3)
    print("Created a sample array 'test':")
    print(test)
    print("-" * 20)


# Swap rows 1 and 2 (remembering that indexing starts at 0)
# The slicing [[1, 0, 2], :] selects the rows in the order of row 1, then row 0, then row 2
# and selects all columns (:)
test[[0, 1], :] = test[[1, 0], :]
print("Array with rows 1 and 2 swapped:")
print(test)

Array with rows 1 and 2 swapped:
[[4 3 5]
 [1 0 2]
 [7 6 8]]


In [ ]:
arr=np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
arr[:,[1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])